# See guide: https://www.bezkoder.com/docker-compose-spring-boot-mysql
# https://spring.io/guides/topicals/spring-boot-docker

version: "3.8"

services:
  postgres-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shybyedb
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  app:
    depends_on:
      - postgres-db
    build: ./
    restart: on-failure
    ports:
      - 8080:9000

volumes:
  db:
